### ISSUE TITLE
[apilot] Power Save Mode 지속 여부 설정 추가?

### ISSUE THREAD

**Issue by ohbeng** [jc01rho-openpilot-BoltEV2019-KoKr/boltpilot#105]
boltpilot 은 시동 끄고 장시간? 지나도 c3 가 계속 sleep mode 에서 대기하는데
apilot 은  boltpilot 과는 다르게 일정시간? 지나면 power off 되는 것 같습니다, 
아침에 시동걸면 항상 부팅하고 있네요.
boltpilot 처럼 Power Save Mode 를 지속 할지 설정 가능하면 좋을 것 같습니다.

**Comment by jc01rho** [comment]
https://github.com/jc01rho-openpilot-BoltEV2019-KoKr/boltpilot/blob/feature/opgm-ap-integration/selfdrive/thermald/power_monitoring.py#L112-L131

보통 여기라인에서 관리를 하는데, 추후 찾아보도록 하겠습니다 :)

**Comment by jc01rho** [comment]
https://github.com/search?q=repo%3Ajc01rho-openpilot-BoltEV2019-KoKr%2Fboltpilot%20%20shutdown&type=code

**Comment by ohbeng** [comment]
제 commit 에 shutdown 시간을 bool 로 잘못가져오는 버그가 하나 있네요
아래 코드에서 self.params.get_bool  ->  self.params.get   으로 수정 부탁드립니다.
https://github.com/jc01rho-openpilot-BoltEV2019-KoKr/boltpilot/blob/feature/opgm-ap-integration/selfdrive/thermald/power_monitoring.py#L123

**Comment by jc01rho** [comment]
@ohbeng 
https://github.com/jc01rho-openpilot-BoltEV2019-KoKr/boltpilot/commit/10159ddb38538ae7d5372f99816deba99cac11c0

반영하였으니 참조 부탁드립니다 :)

**Comment by jc01rho** [comment]
pr 115 에 int() 로 한번 더 wrapping 하신걸 이제봐서, 그쪽으로 한번 더 반영하였습니다.

https://github.com/jc01rho-openpilot-BoltEV2019-KoKr/boltpilot/pull/115/
