### ISSUE TITLE
Requires ACC on latest release

### ISSUE THREAD

**Issue by andyroo-t** [jc01rho-openpilot-BoltEV2019-KoKr/boltpilot#217]
콤마3 이슈 외에 제보를 받고있지 않습니다.
please post only comma3 issues.

**Describe the bug*

Previous release worked great on 2020 Premier. Now pressing set or speed control on wheel gives "enable adaptive cruise to engage". There also is no enable comma pedal setting in the UI.

**To Reproduce**
1. Go to set-
2. Click on set-
3. Scroll down to comma screen

**Expected behavior

As in prior release, expect LKAS to function

**Additional context**

**Comment by jc01rho** [comment]
Thx for report.  I will update the procedure to run(which Toggles need in ui settings, or make default set toggles, ... ) Openpilot.

Anywa, this repository still keeps "Previous release" that you've mentioned. Named v0819-c3

And a.. do you installed comma-Pedal?

**Comment by andyroo-t** [comment]
Thanks!

**Comment by andyroo-t** [comment]
Will be happy to test - just pop me an email

**Comment by jc01rho** [comment]
Here is settings-Toggle page in comma 3,
Written in Korean.

please get a same toggles with my.


![20230724_083904.jpg](https://github.com/jc01rho-openpilot-BoltEV2019-KoKr/boltpilot/assets/4989674/77ce5c75-e307-4734-ad06-1a4ecffcbcd3)
first - "Use Openpilot"
Second (last row in picture )-  EnableRadarTracks




![20230724_083910.jpg](https://github.com/jc01rho-openpilot-BoltEV2019-KoKr/boltpilot/assets/4989674/0e26b652-fc67-4705-85f2-0b631f72e03d)
First -  EnableRadarTracks
Second (below  EnableRadarTracks in picture ) - Warning at lane departure
Third ("미터법 사용" in row) - use metrics
Fourth (see the numeric "24" in row ) - ETA in 24h

**Comment by andyroo-t** [comment]
OK. Thanks.

 I did have OpenPilot enabled, but your second screenshot shows many settings I did not.

I'm traveling in an hour, so am reverting to v0819-c3 for now, but will try it out later this week.

**Comment by andyroo-t** [comment]
Hi,

0.0819-c3 Reversion is working again with autosteer on the 2020. 

Do you have a test checklist or plan I can do so we can add the '20 as tested?

**Comment by jc01rho** [comment]
before the checklist, please tell me that you are using comma3 without CommaPedal? So only steer.

**Comment by andyroo-t** [comment]
Hi,

I have a fairly new Comma3.

Pedal Interceptor board

GM harness from Comma.ai

2020 Premier with LKAS, brake alert, and cruise control (no radar).

Steer still works. I prefer "Torque" vs PID.

Visual ACC also now works (it didn't before...would try to run over cars being followed). It's a bit annoying in its conservatism, so am on the fence on its utility with default settings.

Ran it for 100km just now, probably 80km on highway (100km/h) and 20km city, with final leg of 10km climbing 400m elevation with sharp mountain curves that overwhelm it (as they did before). 

https://m.youtube.com/watch?v=_E2WvCHFMuM

The lane identifier/tracker works very well, just that the steer is too timid to follow it faithfully.

Fake ACC is also a bit dangerous, even though poor drivers would assume it's safer with longer follow distance. Other cars cut in because of the excessive follow distance, forcing an unexpected regen brake (with brake lights) for following cars to react to (a 100km/h to 80km/h aggressive slowing with nothing visible ahead that would have triggered it), in order to maintain that crazy distance. I would cut it by half to 2/3 of present values. I'm not a typical lay, undisciplined, unskilled American driver, lol.

Anyway, I am very happy to have it back working again with the reversion after a few days of it being dead with the update. I'm city driving to/from school to my mountain home, so will take another try at the new release when I get some time in the next week or two.

Meanwhile, I think a good idea to add the 2020 as "tested", assuming I can check off all items on your "go" list. Can do same on the new release in a week or two.

Thank you for the crazy amount of investigation and work you guys put in on this. I'm an EE, so I understand the effort put into this.

cheers,

andy


ps do you know of any comprehensive CAN bus deciphering documentation for the Bolt EV? I'd like to build some hardware for the inverter and charger/battery at some point. An incomplete list is better than the one I don't have.

**Comment by jc01rho** [comment]
thx for detail review.

Embarrassingly, there is no perfect checklist.
But if the speed control and steering control work well, I think that's a test, so we've added BoltEV 2020 to our list of tested vehicles.

The CAN bus deciphering documentation I have does not exist, all CAN stuff is inspired by opgm (https://github.com/opgm/openpilot).

**Comment by jc01rho** [comment]
BoltEV 2020 added to "Tested" with commit
https://github.com/jc01rho-openpilot-BoltEV2019-KoKr/boltpilot/commit/8466f37d4eafbc456503319f32611a38e8e9fcfe

**Comment by andyroo-t** [comment]
Hi,

I forgot to mention (sorry), imperial units works fine in your fork, so you can remove the metric restriction.

cheers,

-andy
