### ISSUE TITLE
"Redneck ACC" ("RACC") fails to disconnect

### ISSUE THREAD

**Issue by andyroo-t** [jc01rho-openpilot-BoltEV2019-KoKr/boltpilot#220]
콤마3 이슈 외에 제보를 받고있지 않습니다.
please post only comma3 issues.

**Describe the bug**

2020 Bolt EV (no factory ACC) in RACC mode decelerates after regen paddle trigger, but fails to come to full stop

**To Reproduce**
1. Go to set- at speed ~80km/h
2. Click on regen paddle
3. Coast down to zero mph (try to)
4. See error - vehicle maintains 40km/h

**Expected behavior

Brake tap causes RACC to disconnect and vehicle regen brakes to zero speed. Regen paddle tap causes RACC to disconnect, vehicle regen brakes, RACC speed target gets set to zero and regen paddle remains enabled. 

**Additional context**
Brake tap is acknowledged RACC disconnect means. But, regen paddle also disconnects RACC and creates expectation of regen braking to zero speed. Instead it has a RACC target arbitrarily set to 40km/h AND the regen paddle does nothing...speed stays constant until brake pedal disconnect.

**Comment by jc01rho** [comment]
unfortunately, I have no idea about redneck. sorry.

**Comment by andyroo-t** [comment]
Video ranged cruise control

The term is from the originator of the code, not mine

**Comment by jc01rho** [comment]
My code of 0819 does not considered RACC thing on that's moments.  I cannot predict RACC is work-able.
Even if some code snippets included for RACC, I didn't checked it for any seconds. ( cuz I am using pedal, ) So, maybe some RACC things deleted by me ( or maybe old-older CAN or opendbc for GM is used . )
