### ISSUE TITLE
Collision Warning persists at Zero Speed

### ISSUE THREAD

**Issue by andyroo-t** [jc01rho-openpilot-BoltEV2019-KoKr/boltpilot#221]
콤마3 이슈 외에 제보를 받고있지 않습니다.
please post only comma3 issues.

**Describe the bug*

Low speed closure on a large vehicle (American van, American pickup truck, medium to heavt duty truck - a vehicle that fills most (>~90%) of the Comma3's road display) generates Red screen on Comma3 collision warning ("Brake! Risk of Collision") which persists despite the Bolt EV having reached zero speed through regen (one pedal driving - do not use brake pedal).

**To Reproduce**
1. Go to within a meter of stopped truck ahead while decelerating with regen paddle only (one pedal driving, do not tough brake pedal)
2. Observe collision alert activate & persist
3. Slow to zero speed with regen paddle only with target of a half meter follow.
4. See error where alert screen persists for up to infinite time (very annoying audio and red screen) until either vehicle ahead moves forward to reduce its size in the Comma3 screen or (I think) if brake pedal cancel (I don't believe the regen pasdle can cancel the alerter).

**Expected behavior**
Vehicle alerts on leading truck's image mostly filling Comma3 screen during one prdal driving. Irrespective of leading truck's image size in Comma3 screen, collision alert cancels when Bolt EV regen brake achieves zero speed or when truck image size on screen gets smaller (Bolt reversing or truck moving forward).

**Additional context**
none

**Comment by jc01rho** [comment]
please tell me this bug occured in branch "0819" ?

**Comment by andyroo-t** [comment]
yes

**Comment by jc01rho** [comment]
collision warning has combind Commas video read model. (model_fcw, planner_fcw)

https://github.com/jc01rho-openpilot-BoltEV2019-KoKr/boltpilot/blob/4701b1aaa5dd189f2cf2bd9ccba5507e249142fc/selfdrive/controls/controlsd.py#L426-L426

for now, I'd recommend disable collision warning.

find "Disable Openpilot FCW" and toggle off :)
